/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author Fame
 */
public class AddDoctorFrame extends javax.swing.JFrame {
    /**
     * Creates new form AddDoctorFrame
     */
    public AddDoctorFrame() {
        super("****ADD DOCTOR****");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDoctorJLabel = new javax.swing.JLabel();
        DoctorIDJLabel = new javax.swing.JLabel();
        DoctorNameJLabel = new javax.swing.JLabel();
        DoctorSpecializationJLabel = new javax.swing.JLabel();
        DoctorIDTextField = new javax.swing.JTextField();
        DoctorNameTextField = new javax.swing.JTextField();
        DoctorSpecializationTextField = new javax.swing.JTextField();
        backJB = new javax.swing.JButton();
        logoutJB = new javax.swing.JButton();
        AddDoctorJB = new javax.swing.JButton();
        FeeJL = new javax.swing.JLabel();
        contactJL = new javax.swing.JLabel();
        feeJField = new javax.swing.JTextField();
        contactJField = new javax.swing.JTextField();
        displayJB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addDoctorJLabel.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        addDoctorJLabel.setForeground(new java.awt.Color(255, 51, 51));
        addDoctorJLabel.setText("ADD DOCTOR");
        getContentPane().add(addDoctorJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        DoctorIDJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DoctorIDJLabel.setForeground(new java.awt.Color(204, 0, 153));
        DoctorIDJLabel.setText("Doctor's ID");
        getContentPane().add(DoctorIDJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        DoctorNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DoctorNameJLabel.setForeground(new java.awt.Color(255, 51, 51));
        DoctorNameJLabel.setText("Doctor's Name");
        getContentPane().add(DoctorNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 85, -1, -1));

        DoctorSpecializationJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DoctorSpecializationJLabel.setForeground(new java.awt.Color(255, 51, 153));
        DoctorSpecializationJLabel.setText("Doctor's Specialization");
        getContentPane().add(DoctorSpecializationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        DoctorIDTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorIDTextFieldMouseClicked(evt);
            }
        });
        getContentPane().add(DoctorIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 230, 30));

        DoctorNameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorNameTextFieldMouseClicked(evt);
            }
        });
        getContentPane().add(DoctorNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 230, 30));

        DoctorSpecializationTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorSpecializationTextFieldMouseClicked(evt);
            }
        });
        getContentPane().add(DoctorSpecializationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 230, 30));

        backJB.setBackground(new java.awt.Color(51, 255, 0));
        backJB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Go-back-icon.png")); // NOI18N
        backJB.setText("BACK");
        backJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBActionPerformed(evt);
            }
        });
        getContentPane().add(backJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 333, 100, 30));

        logoutJB.setBackground(new java.awt.Color(204, 0, 204));
        logoutJB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logoutJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\log out.png")); // NOI18N
        logoutJB.setText("LOGOUT");
        logoutJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJBActionPerformed(evt);
            }
        });
        getContentPane().add(logoutJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 331, 100, 30));

        AddDoctorJB.setBackground(new java.awt.Color(204, 0, 153));
        AddDoctorJB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddDoctorJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\add-icon.png")); // NOI18N
        AddDoctorJB.setText("ADD");
        AddDoctorJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDoctorJBActionPerformed(evt);
            }
        });
        getContentPane().add(AddDoctorJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 90, 30));

        FeeJL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FeeJL.setForeground(new java.awt.Color(51, 153, 0));
        FeeJL.setText("Fee");
        getContentPane().add(FeeJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 55, -1));

        contactJL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        contactJL.setForeground(new java.awt.Color(51, 153, 0));
        contactJL.setText("Contact");
        getContentPane().add(contactJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        feeJField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feeJFieldMouseClicked(evt);
            }
        });
        getContentPane().add(feeJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 230, 30));

        contactJField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactJFieldMouseClicked(evt);
            }
        });
        getContentPane().add(contactJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 230, 30));

        displayJB.setBackground(new java.awt.Color(153, 255, 0));
        displayJB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        displayJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\display.png")); // NOI18N
        displayJB.setText("DISPLAY");
        displayJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayJBActionPerformed(evt);
            }
        });
        getContentPane().add(displayJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\blur-hospital.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBActionPerformed
        // TODO add your handling code here:
        DoctorModuleFrame dmf=new DoctorModuleFrame();
        dmf.setVisible(true);
        dispose();
    }//GEN-LAST:event_backJBActionPerformed

    private void logoutJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJBActionPerformed
        // TODO add your handling code here:
        AdminFrame af=new AdminFrame();
        af.setVisible(true);
        dispose();  
    }//GEN-LAST:event_logoutJBActionPerformed

    private void AddDoctorJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDoctorJBActionPerformed
        // TODO add your handling code here:
            //get data from interface
            try{
             String name=DoctorNameTextField.getText();
            String id=DoctorIDTextField.getText();
             String fee=feeJField.getText();
              String contact=contactJField.getText();
              String specialization=DoctorSpecializationTextField.getText();
              if(name.equals("")||id.equals("")||fee.equals("")||contact.equals("")||specialization.equals("")){
                  throw new NullPointerException();
              }
              else{
                  try{
                      
              int a=Integer.parseInt(id);
              int b=Integer.parseInt(fee);
              //using business class
              Doctor d=new Doctor(name,contact,specialization,a,b);
              //third layer
              FileHandler fh=new FileHandler();
              fh.write(d);
               JOptionPane.showMessageDialog(this, "DATA ADDED SUCCESSFULLY","****CONFIRMATION***",JOptionPane.INFORMATION_MESSAGE);
              DoctorNameTextField.setText("");
              DoctorIDTextField.setText("");
              feeJField.setText("");
              contactJField.setText("");
              DoctorSpecializationTextField.setText("");
            }
                  catch(NumberFormatException e){
JOptionPane.showMessageDialog(this, "NUMBER FORMAT EXCEPTION, ENTER INTEGER IN FIELD ID OR FEE ","**INVALID**",JOptionPane.ERROR_MESSAGE);
            }
            }
            }
            
            catch(NullPointerException e){
                JOptionPane.showMessageDialog(this, "NULL POINTER EXCEPTION OCCURED,ALL FIELDS ARE MANDATORY**FILL ALL THE FIELDS**","**INVALID**",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_AddDoctorJBActionPerformed

    private void displayJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayJBActionPerformed
        // TODO add your handling code here:
         FileHandler f=new FileHandler();
        ArrayList<Doctor> d=f.read();
        ViewDoctorDetailsFrame vdf=new ViewDoctorDetailsFrame();
        vdf.setVisible(true);
       vdf.displayData(d);
        this.dispose();
    }//GEN-LAST:event_displayJBActionPerformed

    private void DoctorNameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorNameTextFieldMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_DoctorNameTextFieldMouseClicked

    private void DoctorIDTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorIDTextFieldMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_DoctorIDTextFieldMouseClicked

    private void feeJFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feeJFieldMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_feeJFieldMouseClicked

    private void contactJFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactJFieldMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_contactJFieldMouseClicked

    private void DoctorSpecializationTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorSpecializationTextFieldMouseClicked
        // TODO add your handling code here:
        DoctorSpecializationTextField.setText("");
    }//GEN-LAST:event_DoctorSpecializationTextFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDoctorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDoctorJB;
    private javax.swing.JLabel DoctorIDJLabel;
    private javax.swing.JTextField DoctorIDTextField;
    private javax.swing.JLabel DoctorNameJLabel;
    private javax.swing.JTextField DoctorNameTextField;
    private javax.swing.JLabel DoctorSpecializationJLabel;
    private javax.swing.JTextField DoctorSpecializationTextField;
    private javax.swing.JLabel FeeJL;
    private javax.swing.JLabel addDoctorJLabel;
    private javax.swing.JButton backJB;
    private javax.swing.JTextField contactJField;
    private javax.swing.JLabel contactJL;
    private javax.swing.JButton displayJB;
    private javax.swing.JTextField feeJField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutJB;
    // End of variables declaration//GEN-END:variables

public javax.swing.JTextField getDoctorIDTextField(){
    return DoctorIDTextField;
}


}

