/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Fame
 */
public class AddPatientFrame extends javax.swing.JFrame {
    /**
     * Creates new form AddPatientFrame
     */
    public AddPatientFrame() {
        super("****ADD PATIENT****");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        addPatientJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        idJLabel = new javax.swing.JLabel();
        genderJLabel = new javax.swing.JLabel();
        ageJLabel = new javax.swing.JLabel();
        diseaseJLabel = new javax.swing.JLabel();
        admitDateJLabel = new javax.swing.JLabel();
        nameJField = new javax.swing.JTextField();
        diseaseJField = new javax.swing.JTextField();
        idJField = new javax.swing.JTextField();
        admitDateJField = new javax.swing.JTextField();
        ageJField = new javax.swing.JTextField();
        addJB = new javax.swing.JButton();
        displayJB = new javax.swing.JButton();
        backJB = new javax.swing.JButton();
        logOutJB = new javax.swing.JButton();
        femaleJRB = new javax.swing.JRadioButton();
        maleJRB = new javax.swing.JRadioButton();
        otherJRB = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addPatientJLabel.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        addPatientJLabel.setForeground(new java.awt.Color(255, 0, 51));
        addPatientJLabel.setText("ADD PATIENT");
        getContentPane().add(addPatientJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 22, -1, -1));

        nameJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameJLabel.setForeground(new java.awt.Color(0, 153, 153));
        nameJLabel.setText("NAME:");
        getContentPane().add(nameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 66, 60, 14));

        idJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idJLabel.setForeground(new java.awt.Color(102, 0, 102));
        idJLabel.setText("ID:");
        getContentPane().add(idJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 103, 44, -1));

        genderJLabel.setBackground(new java.awt.Color(255, 255, 255));
        genderJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderJLabel.setForeground(new java.awt.Color(255, 102, 102));
        genderJLabel.setText("GENDER:");
        getContentPane().add(genderJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 143, -1, -1));

        ageJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ageJLabel.setForeground(new java.awt.Color(255, 51, 153));
        ageJLabel.setText("AGE:");
        getContentPane().add(ageJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        diseaseJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        diseaseJLabel.setForeground(new java.awt.Color(153, 0, 0));
        diseaseJLabel.setText("DISEASE:");
        getContentPane().add(diseaseJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        admitDateJLabel.setBackground(new java.awt.Color(255, 255, 255));
        admitDateJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        admitDateJLabel.setForeground(new java.awt.Color(0, 204, 204));
        admitDateJLabel.setText("ADMIT DATE:");
        getContentPane().add(admitDateJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        nameJField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameJFieldMouseClicked(evt);
            }
        });
        getContentPane().add(nameJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 65, 220, 30));

        diseaseJField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diseaseJFieldMouseClicked(evt);
            }
        });
        getContentPane().add(diseaseJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 210, 30));

        idJField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idJFieldMouseClicked(evt);
            }
        });
        getContentPane().add(idJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 112, 220, 30));

        admitDateJField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admitDateJFieldMouseClicked(evt);
            }
        });
        getContentPane().add(admitDateJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 210, 30));

        ageJField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ageJFieldMouseClicked(evt);
            }
        });
        getContentPane().add(ageJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 210, 30));

        addJB.setBackground(new java.awt.Color(255, 153, 0));
        addJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\add-icon.png")); // NOI18N
        addJB.setText("ADD");
        addJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJBActionPerformed(evt);
            }
        });
        getContentPane().add(addJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 100, 32));

        displayJB.setBackground(new java.awt.Color(153, 204, 0));
        displayJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        displayJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\display.png")); // NOI18N
        displayJB.setText("DISPLAY");
        displayJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayJBActionPerformed(evt);
            }
        });
        getContentPane().add(displayJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, 32));

        backJB.setBackground(new java.awt.Color(102, 255, 0));
        backJB.setFont(backJB.getFont().deriveFont(backJB.getFont().getStyle() | java.awt.Font.BOLD, backJB.getFont().getSize()+3));
        backJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Go-back-icon.png")); // NOI18N
        backJB.setText("BACK");
        backJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBActionPerformed(evt);
            }
        });
        getContentPane().add(backJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, 32));

        logOutJB.setBackground(new java.awt.Color(255, 153, 51));
        logOutJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logOutJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\log out.png")); // NOI18N
        logOutJB.setText("LOG OUT");
        logOutJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutJBActionPerformed(evt);
            }
        });
        getContentPane().add(logOutJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, 32));

        buttonGroup1.add(femaleJRB);
        femaleJRB.setText("Female");
        getContentPane().add(femaleJRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        buttonGroup1.add(maleJRB);
        maleJRB.setText("Male");
        getContentPane().add(maleJRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        buttonGroup1.add(otherJRB);
        otherJRB.setText("Other");
        getContentPane().add(otherJRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\blurred-interior-hospital-clinical.jpg")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBActionPerformed
        // TODO add your handling code here:
        PatientModuleFrame m=new PatientModuleFrame();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backJBActionPerformed

    private void logOutJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutJBActionPerformed
        // TODO add your handling code here:
        AdminFrame af=new AdminFrame();
        af.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutJBActionPerformed

    private void displayJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayJBActionPerformed
        // TODO add your handling code here:
        FileHandlerPatient f=new FileHandlerPatient();
        ArrayList<Patients> p=f.read();
         ViewPatientDetailsFrame vpdf=new ViewPatientDetailsFrame();
        vpdf.setVisible(true);
        vpdf.displayData(p);
        vpdf.logoutJB().setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_displayJBActionPerformed

    private void addJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJBActionPerformed
        // TODO add your handling code here:
          
              //get data from interface
              try{
             String name=nameJField.getText();
            String id=idJField.getText();
             String admitDate=admitDateJField.getText();
             String gender = null;
             if(femaleJRB.isSelected())
                 gender="female";
            else if(maleJRB.isSelected())
                 gender="male";
            else if(otherJRB.isSelected())
                 gender="other";
              String age=ageJField.getText();
              String disease=diseaseJField.getText();
               if(name.equals("")||id.equals("")||age.equals("")||gender.equals("")||disease.equals("")||admitDate.equals("")){
                  throw new NullPointerException();
              }
              else{
                   try{
              int a=Integer.parseInt(id);
              int b=Integer.parseInt(age);
             
                JOptionPane.showMessageDialog(this, "DATA ADDED SUCCESSFULLY","****CONFIRMATION***",JOptionPane.INFORMATION_MESSAGE);
              Patients p = new Patients(name,gender,disease,admitDate,a,b);
              FileHandlerPatient f=new FileHandlerPatient();
              f.write(p);
             nameJField.setText("");
              idJField.setText("");
              maleJRB.setSelected(false);
              femaleJRB.setSelected(false);
              otherJRB.setSelected(false);
              ageJField.setText("");
              diseaseJField.setText("");
              admitDateJField.setText(" ");
              }
                   catch(NumberFormatException e){
                       JOptionPane.showMessageDialog(this, "NUMBER FORMAT EXCEPTION ENTER INTEGER IN FIELDS AGE AND ID","**INVALID**",JOptionPane.ERROR_MESSAGE);
                   }
               }
              }
              catch(NullPointerException e){
JOptionPane.showMessageDialog(this, "NULL POINTER EXCEPTION OCCURED,ALL FIELDS ARE MANDATORY,FILL ALL THE REQUIRED FIELDS","**INVALID**",JOptionPane.ERROR_MESSAGE);
              }
    }//GEN-LAST:event_addJBActionPerformed

    private void nameJFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameJFieldMouseClicked
        // TODO add your handling code here:
        nameJField.setText("");
    }//GEN-LAST:event_nameJFieldMouseClicked

    private void idJFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idJFieldMouseClicked
        // TODO add your handling code here:
        idJField.setText("");
    }//GEN-LAST:event_idJFieldMouseClicked

    private void ageJFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ageJFieldMouseClicked
        // TODO add your handling code here:
        ageJField.setText("");
    }//GEN-LAST:event_ageJFieldMouseClicked

    private void diseaseJFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diseaseJFieldMouseClicked
        // TODO add your handling code here:
        diseaseJField.setText("");
    }//GEN-LAST:event_diseaseJFieldMouseClicked

    private void admitDateJFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admitDateJFieldMouseClicked
        // TODO add your handling code here:
        admitDateJField.setText("");
    }//GEN-LAST:event_admitDateJFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJB;
    private javax.swing.JLabel addPatientJLabel;
    private javax.swing.JTextField admitDateJField;
    private javax.swing.JLabel admitDateJLabel;
    private javax.swing.JTextField ageJField;
    private javax.swing.JLabel ageJLabel;
    private javax.swing.JButton backJB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField diseaseJField;
    private javax.swing.JLabel diseaseJLabel;
    private javax.swing.JButton displayJB;
    private javax.swing.JRadioButton femaleJRB;
    private javax.swing.JLabel genderJLabel;
    private javax.swing.JTextField idJField;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton logOutJB;
    private javax.swing.JRadioButton maleJRB;
    private javax.swing.JTextField nameJField;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JRadioButton otherJRB;
    // End of variables declaration//GEN-END:variables
}
