/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Fame
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        super("****ADMIN LOGIN PAGE****");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminJLabel = new javax.swing.JLabel();
        UsernameJLabel = new javax.swing.JLabel();
        PasswordJLabel = new javax.swing.JLabel();
        UsernameJTextField = new javax.swing.JTextField();
        LoginJB = new javax.swing.JButton();
        BackJB = new javax.swing.JButton();
        passwordJPassField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminJLabel.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        adminJLabel.setForeground(new java.awt.Color(204, 204, 0));
        adminJLabel.setText("ADMIN LOGIN");
        getContentPane().add(adminJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        UsernameJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UsernameJLabel.setForeground(new java.awt.Color(204, 102, 0));
        UsernameJLabel.setText("USERNAME");
        getContentPane().add(UsernameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        PasswordJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PasswordJLabel.setForeground(new java.awt.Color(204, 102, 0));
        PasswordJLabel.setText("PASSWORD");
        getContentPane().add(PasswordJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        UsernameJTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsernameJTextFieldMouseClicked(evt);
            }
        });
        getContentPane().add(UsernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 250, 40));

        LoginJB.setBackground(new java.awt.Color(204, 204, 0));
        LoginJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Other-Power-Log-Off-Metro-icon.png")); // NOI18N
        LoginJB.setText("LOG IN");
        LoginJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginJBActionPerformed(evt);
            }
        });
        getContentPane().add(LoginJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 120, 50));

        BackJB.setBackground(new java.awt.Color(204, 204, 0));
        BackJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Go-back-icon.png")); // NOI18N
        BackJB.setText("BACK");
        BackJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJBActionPerformed(evt);
            }
        });
        getContentPane().add(BackJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 120, 50));
        getContentPane().add(passwordJPassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 250, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\long-hospital-bright-corridor-rooms.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJBActionPerformed
        // TODO add your handling code here:
        Welcome w=new Welcome();
        w.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackJBActionPerformed

    private void LoginJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginJBActionPerformed
        // TODO add your handling code here:
        //business layer
        Admin adm=new Admin();
        String text1=UsernameJTextField.getText();
        String text2=passwordJPassField.getText();
        try{
        if(text1.equals("")||text2.equals(""))
        {
            throw new NullPointerException();
        }
        
         else{
                if(!text1.equals(adm.getUsername())){
                    JOptionPane.showMessageDialog(null,"INCORRECT USERNAME ","****INVALID****",JOptionPane.CANCEL_OPTION);
             
                }
                  else if(!text2.equals(adm.getPassword())){
                    JOptionPane.showMessageDialog(null,"INCORRECT PASSWARD","****INVALID****",JOptionPane.CANCEL_OPTION);
                    }
        }
        
           
            if(text1.equals(adm.getUsername())&&text2.equals(adm.getPassword())){
         JOptionPane.showMessageDialog(null, "YOU HAVE SUCCESSFULLY LOGGED IN","****CONFIRMATION****",JOptionPane.INFORMATION_MESSAGE);
         this.dispose();
         Modules m=new Modules();
         m.setVisible(true);
            }  
        } 
        
        catch(NullPointerException e){
           JOptionPane.showMessageDialog(null,"NULL POINTER EXCEPTION,**FILL BOTH FIELDS**");
        }
    }//GEN-LAST:event_LoginJBActionPerformed

    private void UsernameJTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameJTextFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameJTextFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJB;
    private javax.swing.JButton LoginJB;
    private javax.swing.JLabel PasswordJLabel;
    private javax.swing.JLabel UsernameJLabel;
    private javax.swing.JTextField UsernameJTextField;
    private javax.swing.JLabel adminJLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passwordJPassField;
    // End of variables declaration//GEN-END:variables
}
