/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Fame
 */
public class ApplyForAppointment extends javax.swing.JFrame {

    /**
     * Creates new form ApplyForAppointment
     */
    public ApplyForAppointment() {
        super("****APPLY FOR APPOINTMENT****");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        applyJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        idJLabel = new javax.swing.JLabel();
        genderJLabel = new javax.swing.JLabel();
        ageJLabel = new javax.swing.JLabel();
        nameJField = new javax.swing.JTextField();
        idJField = new javax.swing.JTextField();
        ageJField = new javax.swing.JTextField();
        confirmJB = new javax.swing.JButton();
        backJB = new javax.swing.JButton();
        diseaseJLabel = new javax.swing.JLabel();
        maleJRB = new javax.swing.JRadioButton();
        femaleJRB = new javax.swing.JRadioButton();
        otherJRB = new javax.swing.JRadioButton();
        diseaseJField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        applyJLabel.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        applyJLabel.setForeground(new java.awt.Color(153, 51, 255));
        applyJLabel.setText("APPLY FOR APPOINTMENT");
        getContentPane().add(applyJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 11, -1, -1));

        nameJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameJLabel.setForeground(new java.awt.Color(255, 102, 0));
        nameJLabel.setText("NAME:");
        getContentPane().add(nameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 59, -1, -1));

        idJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idJLabel.setForeground(new java.awt.Color(204, 0, 153));
        idJLabel.setText("ID:");
        getContentPane().add(idJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 116, -1, -1));

        genderJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderJLabel.setForeground(new java.awt.Color(255, 0, 153));
        genderJLabel.setText("GENDER:");
        getContentPane().add(genderJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 156, -1, -1));

        ageJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ageJLabel.setForeground(new java.awt.Color(0, 153, 153));
        ageJLabel.setText("AGE:");
        getContentPane().add(ageJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 195, -1, -1));
        getContentPane().add(nameJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 54, 194, 30));
        getContentPane().add(idJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 111, 194, 31));
        getContentPane().add(ageJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 191, 194, 28));

        confirmJB.setBackground(new java.awt.Color(255, 51, 153));
        confirmJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Done-icon.png")); // NOI18N
        confirmJB.setText("CONFIRM");
        confirmJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmJBActionPerformed(evt);
            }
        });
        getContentPane().add(confirmJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 132, 39));

        backJB.setBackground(new java.awt.Color(51, 255, 51));
        backJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Go-back-icon.png")); // NOI18N
        backJB.setText("BACK");
        backJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBActionPerformed(evt);
            }
        });
        getContentPane().add(backJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 130, 39));

        diseaseJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        diseaseJLabel.setForeground(new java.awt.Color(255, 0, 0));
        diseaseJLabel.setText("DISEASE:");
        getContentPane().add(diseaseJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        buttonGroup1.add(maleJRB);
        maleJRB.setText("MALE");
        getContentPane().add(maleJRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        buttonGroup1.add(femaleJRB);
        femaleJRB.setText("FEMALE");
        getContentPane().add(femaleJRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        buttonGroup1.add(otherJRB);
        otherJRB.setText("OTHER");
        getContentPane().add(otherJRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));
        getContentPane().add(diseaseJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 200, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\apply for appointment.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmJBActionPerformed
        // TODO add your handling code here:
        try{
         String name=nameJField.getText();
            String id=idJField.getText();
             String gender = null;
             if(femaleJRB.isSelected())
                 gender="female";
            else if(maleJRB.isSelected())
                 gender="male";
            else if(otherJRB.isSelected())
                 gender="other";
              String age=ageJField.getText();
              String disease=diseaseJField.getText();
              if(name.equals("")||id.equals("")||gender.equals("")||age.equals("")||disease.equals("")){
                  throw new NullPointerException();
              }
              else{
                  try{
              int a=Integer.parseInt(id);
              int b=Integer.parseInt(age);
              JOptionPane.showMessageDialog(this,"YOUR APPOINTMENT HAS BEEN CONFIRMED","***CONFIRMATION***",JOptionPane.INFORMATION_MESSAGE);
              Patients p = new Patients(name,gender,disease,a,b);
              FileHandlerPatient f=new FileHandlerPatient();
              f.write(p);
             nameJField.setText("");
              idJField.setText("");
              maleJRB.setSelected(false);
              femaleJRB.setSelected(false);
              otherJRB.setSelected(false);
              ageJField.setText("");
              diseaseJField.setText("");
        }
                  catch(NumberFormatException e){
                      JOptionPane.showMessageDialog(this, "NUMBER FORMAT EXCEPTION OCCURED,**ENTER INTEGER IN FIELDS AGE AND ID**","**INVALID**",JOptionPane.ERROR_MESSAGE);
                  }
        }
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, "NULL POINTER EXCEPTION,ALL FIELDS ARE MANDATORY, FILL ALL FIELDS","**INVALID**",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_confirmJBActionPerformed
public javax.swing.JTextField nameJField(){
    return nameJField;
}
public javax.swing.JTextField idJField(){
    return idJField;
}
public javax.swing.JTextField ageJField(){
    return ageJField;
}
public javax.swing.JTextField diseaseJField(){
    return diseaseJField;
}
    private void backJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBActionPerformed
        // TODO add your handling code here:
        PatientFunctionFrame pff=new PatientFunctionFrame();
        pff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplyForAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplyForAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplyForAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplyForAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplyForAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageJField;
    private javax.swing.JLabel ageJLabel;
    private javax.swing.JLabel applyJLabel;
    private javax.swing.JButton backJB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton confirmJB;
    private javax.swing.JTextField diseaseJField;
    private javax.swing.JLabel diseaseJLabel;
    private javax.swing.JRadioButton femaleJRB;
    private javax.swing.JLabel genderJLabel;
    private javax.swing.JTextField idJField;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton maleJRB;
    private javax.swing.JTextField nameJField;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JRadioButton otherJRB;
    // End of variables declaration//GEN-END:variables
}
