/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import java.awt.ComponentOrientation;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Fame
 */
public class DoctorModuleFrame extends javax.swing.JFrame {
    /**
     * Creates new form DoctorModuleFrame
     */
    public DoctorModuleFrame() {
        super("****ADMIN MODULES****");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminModulesJLabel = new javax.swing.JLabel();
        AddDoctorJB = new javax.swing.JButton();
        ViewRecordsJB = new javax.swing.JButton();
        updateJB = new javax.swing.JButton();
        deleteJB = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminModulesJLabel.setBackground(new java.awt.Color(153, 0, 153));
        adminModulesJLabel.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        adminModulesJLabel.setForeground(new java.awt.Color(255, 51, 102));
        adminModulesJLabel.setText("ADMIN MODULES");
        getContentPane().add(adminModulesJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        AddDoctorJB.setBackground(new java.awt.Color(255, 102, 102));
        AddDoctorJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddDoctorJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\add-icon.png")); // NOI18N
        AddDoctorJB.setText("ADD DOCTOR");
        AddDoctorJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDoctorJBActionPerformed(evt);
            }
        });
        getContentPane().add(AddDoctorJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 190, 40));

        ViewRecordsJB.setBackground(new java.awt.Color(255, 102, 102));
        ViewRecordsJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ViewRecordsJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\display.png")); // NOI18N
        ViewRecordsJB.setText("VIEW RECORDS");
        ViewRecordsJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRecordsJBActionPerformed(evt);
            }
        });
        getContentPane().add(ViewRecordsJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 190, 40));

        updateJB.setBackground(new java.awt.Color(255, 102, 102));
        updateJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\update.png")); // NOI18N
        updateJB.setText("UPDATE DETAILS");
        updateJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJBActionPerformed(evt);
            }
        });
        getContentPane().add(updateJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 190, 40));

        deleteJB.setBackground(new java.awt.Color(255, 102, 102));
        deleteJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Trash-can-icon.png")); // NOI18N
        deleteJB.setText("DELETE DOCTOR");
        deleteJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJBActionPerformed(evt);
            }
        });
        getContentPane().add(deleteJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 190, 40));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Go-back-icon.png")); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 120, 30));

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\log out.png")); // NOI18N
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\smart doctor.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Modules m=new Modules();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AdminFrame f=new AdminFrame();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AddDoctorJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDoctorJBActionPerformed
        // TODO add your handling code here:
        
        AddDoctorFrame adf=new AddDoctorFrame();
        adf.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_AddDoctorJBActionPerformed

    private void updateJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJBActionPerformed
        // TODO add your handling code here:
       UpdateDoctorFrame udf= new UpdateDoctorFrame();
       udf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updateJBActionPerformed

    private void deleteJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJBActionPerformed
        // TODO add your handling code here:
        FileHandler f=new FileHandler();
        ArrayList<Doctor> d=f.read();
        ViewDoctorDetailsFrame vdf=new ViewDoctorDetailsFrame();
        vdf.setVisible(true);
        this.dispose();
        vdf.displayData(d);
        JOptionPane.showMessageDialog(this, "SELECT ANY SINGLE ROW FOR DELETION!!!!","Info Message",JOptionPane.INFORMATION_MESSAGE);
                
    }//GEN-LAST:event_deleteJBActionPerformed

    private void ViewRecordsJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRecordsJBActionPerformed
        // TODO add your handling code here:
        FileHandler fh=new FileHandler();
        ArrayList<Doctor> p=fh.read();
        ViewDoctorDetailsFrame vpdf=new ViewDoctorDetailsFrame();
        vpdf.setVisible(true);
       vpdf.displayData(p);
        this.dispose();

    }//GEN-LAST:event_ViewRecordsJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorModuleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorModuleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorModuleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorModuleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorModuleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDoctorJB;
    private javax.swing.JButton ViewRecordsJB;
    private javax.swing.JLabel adminModulesJLabel;
    private javax.swing.JButton deleteJB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton updateJB;
    // End of variables declaration//GEN-END:variables
}
