/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

/**
 *
 * @author Fame
 */
public class DoctorFunctionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form DoctorFunctionsFrame
     */
    public DoctorFunctionsFrame() {
        super("****DOCTORS MODULES****");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPatientDetailsJB = new javax.swing.JButton();
        writePrescriptionJB = new javax.swing.JButton();
        doctorModulesJLabel = new javax.swing.JLabel();
        backJB = new javax.swing.JButton();
        viewAppointmentJB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewPatientDetailsJB.setBackground(new java.awt.Color(255, 153, 102));
        viewPatientDetailsJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewPatientDetailsJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\display.png")); // NOI18N
        viewPatientDetailsJB.setText("VIEW PATIENT DETAILS");
        viewPatientDetailsJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatientDetailsJBActionPerformed(evt);
            }
        });
        getContentPane().add(viewPatientDetailsJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 240, 44));

        writePrescriptionJB.setBackground(new java.awt.Color(153, 153, 255));
        writePrescriptionJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        writePrescriptionJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\write prescription.png")); // NOI18N
        writePrescriptionJB.setText("WRITE PRESCRIPTION");
        writePrescriptionJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writePrescriptionJBActionPerformed(evt);
            }
        });
        getContentPane().add(writePrescriptionJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 240, 48));

        doctorModulesJLabel.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        doctorModulesJLabel.setForeground(new java.awt.Color(255, 51, 102));
        doctorModulesJLabel.setText("DOCTOR'S MODULES");
        getContentPane().add(doctorModulesJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 20, -1, -1));

        backJB.setBackground(new java.awt.Color(204, 153, 255));
        backJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Go-back-icon.png")); // NOI18N
        backJB.setText("BACK");
        backJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBActionPerformed(evt);
            }
        });
        getContentPane().add(backJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, 33));

        viewAppointmentJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewAppointmentJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\display.png")); // NOI18N
        viewAppointmentJB.setText("VIEW APPOINTMENT");
        viewAppointmentJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAppointmentJBActionPerformed(evt);
            }
        });
        getContentPane().add(viewAppointmentJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 240, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\DOCTOR FUNCTION.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBActionPerformed
        // TODO add your handling code here:
        DoctorStartFrame dsf=new DoctorStartFrame();
        dsf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backJBActionPerformed

    private void viewPatientDetailsJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPatientDetailsJBActionPerformed
        // TODO add your handling code here:
        ViewPatientDetails vpd=new ViewPatientDetails();
        vpd.setVisible(true);
        vpd.backJB().setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_viewPatientDetailsJBActionPerformed

    private void writePrescriptionJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writePrescriptionJBActionPerformed
        // TODO add your handling code here:
        WritePrescription wp=new WritePrescription();
        wp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_writePrescriptionJBActionPerformed

    private void viewAppointmentJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAppointmentJBActionPerformed
        // TODO add your handling code here:
        ViewPatientDetailsFrame vpdf=new ViewPatientDetailsFrame();
        vpdf.setVisible(true);
        vpdf.backJB().setEnabled(false);
        vpdf.deleteJB().setEnabled(false);
        vpdf.billJB().setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_viewAppointmentJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorFunctionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorFunctionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorFunctionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorFunctionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorFunctionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJB;
    private javax.swing.JLabel doctorModulesJLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton viewAppointmentJB;
    private javax.swing.JButton viewPatientDetailsJB;
    private javax.swing.JButton writePrescriptionJB;
    // End of variables declaration//GEN-END:variables
}
