/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

/**
 *
 * @author Fame
 */
public class HospitalFrame extends javax.swing.JFrame {

    /**
     * Creates new form HospitalFrame
     */
    public HospitalFrame() {
        super("****WELCOME TO PIMS HOSPITAL****");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pimsHospitalJLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        phoneJLabel = new javax.swing.JLabel();
        AffiliatedUniLabel = new javax.swing.JLabel();
        FoundedLabel = new javax.swing.JLabel();
        HoursLabel = new javax.swing.JLabel();
        fundingJLabel = new javax.swing.JLabel();
        monoJLabel = new javax.swing.JLabel();
        NextJButton = new javax.swing.JButton();
        pictureJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pimsHospitalJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pimsHospitalJLabel.setForeground(new java.awt.Color(0, 0, 204));
        pimsHospitalJLabel.setText("PIMS HOSPITAL");
        getContentPane().add(pimsHospitalJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        AddressLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddressLabel.setForeground(new java.awt.Color(255, 0, 0));
        AddressLabel.setText("Address: Ibn-e-Sina Rd, G-8/3 G 8/3 G-8, Islamabad");
        getContentPane().add(AddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 329, -1, -1));

        phoneJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phoneJLabel.setText("Phone: (051) 9261170 ");
        getContentPane().add(phoneJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, 23));

        AffiliatedUniLabel.setBackground(new java.awt.Color(255, 0, 153));
        AffiliatedUniLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AffiliatedUniLabel.setText("Affiliated university: Shaheed Zulfiqar Ali Bhutto ");
        getContentPane().add(AffiliatedUniLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, 14));

        FoundedLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FoundedLabel.setForeground(new java.awt.Color(0, 102, 102));
        FoundedLabel.setText("Founded: 1985");
        getContentPane().add(FoundedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        HoursLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        HoursLabel.setForeground(new java.awt.Color(51, 0, 153));
        HoursLabel.setText("Hours:  Closed ⋅ Opens 8AM Mon ");
        getContentPane().add(HoursLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        fundingJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fundingJLabel.setForeground(new java.awt.Color(255, 0, 0));
        fundingJLabel.setText("Funding: Government hospital");
        getContentPane().add(fundingJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        monoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/Images/PIMS LOGO.jpg"))); // NOI18N
        monoJLabel.setText("jLabel6");
        getContentPane().add(monoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 196, -1));

        NextJButton.setBackground(new java.awt.Color(255, 153, 153));
        NextJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NextJButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\next.png")); // NOI18N
        NextJButton.setText("NEXT");
        NextJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NextJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 120, 30));

        pictureJLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\city hospital.jpg")); // NOI18N
        getContentPane().add(pictureJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NextJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
       Welcome w=new Welcome();
        w.setVisible(true);
    }//GEN-LAST:event_NextJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JLabel AffiliatedUniLabel;
    private javax.swing.JLabel FoundedLabel;
    private javax.swing.JLabel HoursLabel;
    private javax.swing.JButton NextJButton;
    private javax.swing.JLabel fundingJLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel monoJLabel;
    private javax.swing.JLabel phoneJLabel;
    private javax.swing.JLabel pictureJLabel;
    private javax.swing.JLabel pimsHospitalJLabel;
    // End of variables declaration//GEN-END:variables
}
