/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

/**
 *
 * @author Fame
 */
public class Modules extends javax.swing.JFrame {

    /**
     * Creates new form Modules
     */
    public Modules() {
            super("****ADMIN MODULES****");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeJLabel = new javax.swing.JLabel();
        DoctorModuleJB = new javax.swing.JButton();
        PatientModuleJB = new javax.swing.JButton();
        LogoutJB = new javax.swing.JButton();
        pictureJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeJLabel.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        welcomeJLabel.setForeground(new java.awt.Color(255, 0, 0));
        welcomeJLabel.setText("WELCOME TO HOSPITAL");
        getContentPane().add(welcomeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        DoctorModuleJB.setBackground(new java.awt.Color(255, 204, 51));
        DoctorModuleJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DoctorModuleJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\doctor modules.png")); // NOI18N
        DoctorModuleJB.setText("Doctor's Modules");
        DoctorModuleJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorModuleJBActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorModuleJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 71, 190, 50));

        PatientModuleJB.setBackground(new java.awt.Color(255, 204, 0));
        PatientModuleJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PatientModuleJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\patient modules.png")); // NOI18N
        PatientModuleJB.setText("Patient's Modules");
        PatientModuleJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientModuleJBActionPerformed(evt);
            }
        });
        getContentPane().add(PatientModuleJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 135, 190, 50));

        LogoutJB.setBackground(new java.awt.Color(204, 204, 0));
        LogoutJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LogoutJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\log out.png")); // NOI18N
        LogoutJB.setText("LOGOUT");
        LogoutJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutJBActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 130, 30));

        pictureJLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\medical-science-background-healthcare-industry.jpg")); // NOI18N
        getContentPane().add(pictureJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 280));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutJBActionPerformed
        // TODO add your handling code here:
        AdminFrame a=new AdminFrame();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutJBActionPerformed

    private void DoctorModuleJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorModuleJBActionPerformed
        // TODO add your handling code here:
        DoctorModuleFrame d=new DoctorModuleFrame();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_DoctorModuleJBActionPerformed

    private void PatientModuleJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientModuleJBActionPerformed
        // TODO add your handling code here:
         PatientModuleFrame p=new PatientModuleFrame();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_PatientModuleJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modules().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoctorModuleJB;
    private javax.swing.JButton LogoutJB;
    private javax.swing.JButton PatientModuleJB;
    private javax.swing.JLabel pictureJLabel;
    private javax.swing.JLabel welcomeJLabel;
    // End of variables declaration//GEN-END:variables
}
