/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

/**
 *
 * @author Fame
 */
public class PatientFunctionFrame extends javax.swing.JFrame {

    /**
     * Creates new form PatientFunctionFrame
     */
    public PatientFunctionFrame() {
        super("****PATIENT MODULES****");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientModulesJLabel = new javax.swing.JLabel();
        applyAppointmentJB = new javax.swing.JButton();
        viewDoctorProfileJB = new javax.swing.JButton();
        viewOwnProfileJB = new javax.swing.JButton();
        backJB = new javax.swing.JButton();
        pictureJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientModulesJLabel.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        patientModulesJLabel.setForeground(new java.awt.Color(153, 0, 153));
        patientModulesJLabel.setText("PATIENT'S MODULES");
        getContentPane().add(patientModulesJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        applyAppointmentJB.setBackground(new java.awt.Color(255, 0, 0));
        applyAppointmentJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        applyAppointmentJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\apply appointment icon.png")); // NOI18N
        applyAppointmentJB.setText("APPLY FOR APPOINTMENT");
        applyAppointmentJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyAppointmentJBActionPerformed(evt);
            }
        });
        getContentPane().add(applyAppointmentJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 82, 260, 34));

        viewDoctorProfileJB.setBackground(new java.awt.Color(255, 153, 153));
        viewDoctorProfileJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewDoctorProfileJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\display.png")); // NOI18N
        viewDoctorProfileJB.setText("VIEW DOCTOR PROFILE");
        viewDoctorProfileJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDoctorProfileJBActionPerformed(evt);
            }
        });
        getContentPane().add(viewDoctorProfileJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 260, 39));

        viewOwnProfileJB.setBackground(new java.awt.Color(255, 204, 102));
        viewOwnProfileJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewOwnProfileJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\display.png")); // NOI18N
        viewOwnProfileJB.setText("VIEW OWN PROFILE");
        viewOwnProfileJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOwnProfileJBActionPerformed(evt);
            }
        });
        getContentPane().add(viewOwnProfileJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 222, 260, 38));

        backJB.setBackground(new java.awt.Color(102, 255, 51));
        backJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\back-icon.png")); // NOI18N
        backJB.setText("BACK");
        backJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBActionPerformed(evt);
            }
        });
        getContentPane().add(backJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 278, 100, 32));

        pictureJLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\doctor-stethoscope-hand-checking-.jpg")); // NOI18N
        getContentPane().add(pictureJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBActionPerformed
        // TODO add your handling code here:
        
        Welcome w=new Welcome();
        w.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backJBActionPerformed

    private void applyAppointmentJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyAppointmentJBActionPerformed
        // TODO add your handling code here:
        ApplyForAppointment afa=new ApplyForAppointment();
        afa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_applyAppointmentJBActionPerformed

    private void viewDoctorProfileJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDoctorProfileJBActionPerformed
        // TODO add your handling code here:
        ViewDoctorProfile vdp=new ViewDoctorProfile();
        vdp.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_viewDoctorProfileJBActionPerformed

    private void viewOwnProfileJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOwnProfileJBActionPerformed
        // TODO add your handling code here:
        ViewPatientDetails vpp=new ViewPatientDetails();
        vpp.setVisible(true);
        vpp.logoutJB().setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_viewOwnProfileJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientFunctionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientFunctionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientFunctionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientFunctionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientFunctionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyAppointmentJB;
    private javax.swing.JButton backJB;
    private javax.swing.JLabel patientModulesJLabel;
    private javax.swing.JLabel pictureJLabel;
    private javax.swing.JButton viewDoctorProfileJB;
    private javax.swing.JButton viewOwnProfileJB;
    // End of variables declaration//GEN-END:variables
}
