/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Fame
 */
public class PatientModuleFrame extends javax.swing.JFrame {

    /**
     * Creates new form PatientModuleFrame
     */
    public PatientModuleFrame() {
        super("****ADMIN MODULES****");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPatientJB = new javax.swing.JButton();
        viewRecordsJB = new javax.swing.JButton();
        updateDetailsJB = new javax.swing.JButton();
        deletePatientJB = new javax.swing.JButton();
        backJB = new javax.swing.JButton();
        logOutJB = new javax.swing.JButton();
        adminModulesJLabel = new javax.swing.JLabel();
        pictureJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addPatientJB.setBackground(new java.awt.Color(255, 153, 51));
        addPatientJB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addPatientJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\add-icon.png")); // NOI18N
        addPatientJB.setText("ADD PATIENT");
        addPatientJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientJBActionPerformed(evt);
            }
        });
        getContentPane().add(addPatientJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 250, 40));

        viewRecordsJB.setBackground(new java.awt.Color(255, 153, 51));
        viewRecordsJB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewRecordsJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\display.png")); // NOI18N
        viewRecordsJB.setText("VIEW RECORDS");
        viewRecordsJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRecordsJBActionPerformed(evt);
            }
        });
        getContentPane().add(viewRecordsJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 250, 40));

        updateDetailsJB.setBackground(new java.awt.Color(255, 153, 51));
        updateDetailsJB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateDetailsJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\update.png")); // NOI18N
        updateDetailsJB.setText("UPDATE DETAILS");
        updateDetailsJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDetailsJBActionPerformed(evt);
            }
        });
        getContentPane().add(updateDetailsJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 250, 40));

        deletePatientJB.setBackground(new java.awt.Color(255, 153, 51));
        deletePatientJB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deletePatientJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Trash-can-icon.png")); // NOI18N
        deletePatientJB.setText("DISCHARGE PATIENT");
        deletePatientJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePatientJBActionPerformed(evt);
            }
        });
        getContentPane().add(deletePatientJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 250, 40));

        backJB.setBackground(new java.awt.Color(102, 102, 255));
        backJB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Go-back-icon.png")); // NOI18N
        backJB.setText("BACK");
        backJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBActionPerformed(evt);
            }
        });
        getContentPane().add(backJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 313, 100, 30));

        logOutJB.setBackground(new java.awt.Color(255, 102, 102));
        logOutJB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logOutJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\log out.png")); // NOI18N
        logOutJB.setText("LOGOUT");
        logOutJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutJBActionPerformed(evt);
            }
        });
        getContentPane().add(logOutJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, 30));

        adminModulesJLabel.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        adminModulesJLabel.setForeground(new java.awt.Color(255, 0, 51));
        adminModulesJLabel.setText("ADMIN MODULES");
        getContentPane().add(adminModulesJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 320, 30));

        pictureJLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\computerized management system.png")); // NOI18N
        getContentPane().add(pictureJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBActionPerformed
        // TODO add your handling code here:
        Modules m=new Modules();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backJBActionPerformed

    private void logOutJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutJBActionPerformed
        // TODO add your handling code here:
        AdminFrame af=new AdminFrame();
        af.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutJBActionPerformed

    private void addPatientJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientJBActionPerformed
        // TODO add your handling code here:
        AddPatientFrame apf=new AddPatientFrame();
        apf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addPatientJBActionPerformed

    private void viewRecordsJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRecordsJBActionPerformed
        // TODO add your handling code here:
        
          FileHandlerPatient fh=new FileHandlerPatient();
        ArrayList<Patients> p=fh.read();
        ViewPatientDetailsFrame vpdf=new ViewPatientDetailsFrame();
        vpdf.setVisible(true);
       vpdf.displayData(p);
       vpdf.logoutJB().setEnabled(false);
        this.dispose();
        
    }//GEN-LAST:event_viewRecordsJBActionPerformed

    private void deletePatientJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePatientJBActionPerformed
        // TODO add your handling code here:
       
         FileHandlerPatient fh=new FileHandlerPatient();
        ArrayList<Patients> p=fh.read();
        ViewPatientDetailsFrame vpdf=new ViewPatientDetailsFrame();
        vpdf.setVisible(true);
         this.dispose();
         vpdf.logoutJB().setEnabled(false);
         JOptionPane.showMessageDialog(this, "SELECT ANY SINGLE ROW FOR DELETEION!!!!","**INFO MEASSAGE***",JOptionPane.INFORMATION_MESSAGE);
        vpdf.displayData(p);
    }//GEN-LAST:event_deletePatientJBActionPerformed

    private void updateDetailsJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDetailsJBActionPerformed
        // TODO add your handling code here:
        new UpdatePatientFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updateDetailsJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientModuleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientModuleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientModuleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientModuleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientModuleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientJB;
    private javax.swing.JLabel adminModulesJLabel;
    private javax.swing.JButton backJB;
    private javax.swing.JButton deletePatientJB;
    private javax.swing.JButton logOutJB;
    private javax.swing.JLabel pictureJLabel;
    private javax.swing.JButton updateDetailsJB;
    private javax.swing.JButton viewRecordsJB;
    // End of variables declaration//GEN-END:variables
}
