/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Fame
 */
public class ViewPatientDetailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewPatientDetailsFrame
     */
    public ViewPatientDetailsFrame() {
        super("****PATIENT DETAILS****");
        initComponents();
    }
public void displayData(ArrayList <Patients>s){
       String array[] = new String[6];
        DefaultTableModel tb = (DefaultTableModel)patientDetailsJTable.getModel();
        for(Patients i: s){
            array[0] = i.getName();
            array[1] = i.getGender();
            array[2] = i.getDisease();
            array[3] = i.getAdmitDate();
            array[4] = i.getId()+"";
            array[5] = i.getAge()+"";
            tb.addRow(array);
        }
        
    }
    public void deleteData(){
        DefaultTableModel tb = (DefaultTableModel)patientDetailsJTable.getModel();
        //jTable1.gets
        int i = patientDetailsJTable.getSelectedRow();
        
        String name = tb.getValueAt(i, 0) + "";
         String gender = tb.getValueAt(i, 1) + "";
          String disease = tb.getValueAt(i, 2) + "";
           String admitDate = tb.getValueAt(i, 3) + "";
        int id = Integer.parseInt(tb.getValueAt(i, 4)+"");
        int age = Integer.parseInt(tb.getValueAt(i, 5)+"");
        System.out.print("\n"+name+"\n"+gender+"\n"+disease+"\n"+admitDate+"\n"+id+"\n"+age);
        Patients s = new Patients(name,gender,disease,admitDate, id, age);
        FileHandlerPatient f = new FileHandlerPatient();
        f.delete(s);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJB = new javax.swing.JButton();
        deleteJB = new javax.swing.JButton();
        billJB = new javax.swing.JButton();
        refreshJB = new javax.swing.JButton();
        logoutJB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientDetailsJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJB.setBackground(new java.awt.Color(153, 255, 153));
        backJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Go-back-icon.png")); // NOI18N
        backJB.setText("BACK");
        backJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBActionPerformed(evt);
            }
        });
        getContentPane().add(backJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        deleteJB.setBackground(new java.awt.Color(255, 102, 51));
        deleteJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Trash-can-icon.png")); // NOI18N
        deleteJB.setText("DELETE");
        deleteJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJBActionPerformed(evt);
            }
        });
        getContentPane().add(deleteJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, 30));

        billJB.setBackground(new java.awt.Color(102, 255, 0));
        billJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        billJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\bill.png")); // NOI18N
        billJB.setText("BILL");
        billJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billJBActionPerformed(evt);
            }
        });
        getContentPane().add(billJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 100, 31));

        refreshJB.setBackground(new java.awt.Color(255, 102, 51));
        refreshJB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refreshJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\refresh-icon.png")); // NOI18N
        refreshJB.setText("REFRESH");
        refreshJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJBActionPerformed(evt);
            }
        });
        getContentPane().add(refreshJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 130, 29));

        logoutJB.setBackground(new java.awt.Color(255, 102, 51));
        logoutJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\log out.png")); // NOI18N
        logoutJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJBActionPerformed(evt);
            }
        });
        getContentPane().add(logoutJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 100, 40));

        patientDetailsJTable.setBackground(new java.awt.Color(255, 153, 153));
        patientDetailsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "GENDER", "DISEASE", "ADMIT DATE", "ID", "AGE"
            }
        ));
        jScrollPane1.setViewportView(patientDetailsJTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 124, -1, 107));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("VIEW PATIENT DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\stock-photo-background-of-senior-patient-with-nurse-checking-blood-presure-overlay-with-health-insurance-1481883929.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBActionPerformed
        // TODO add your handling code here:
        PatientModuleFrame pmf=new PatientModuleFrame();
        pmf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backJBActionPerformed

    private void logoutJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJBActionPerformed
 
        // TODO add your handling code here:
        DoctorFunctionsFrame dff=new DoctorFunctionsFrame();
        dff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutJBActionPerformed

    private void refreshJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJBActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel)patientDetailsJTable.getModel();
        tb.setRowCount(0);
        FileHandlerPatient f = new FileHandlerPatient();
        ArrayList <Patients> s = f.read();
        this.displayData(s);
    }//GEN-LAST:event_refreshJBActionPerformed

    private void billJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billJBActionPerformed
        // TODO add your handling code here:
        BillFrame bf=new BillFrame();
        bf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_billJBActionPerformed

    private void deleteJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJBActionPerformed
        // TODO add your handling code here:
        if(patientDetailsJTable.getSelectedRowCount()==1){
        int option=JOptionPane.showConfirmDialog(this, "ARE YOU SURE YOU WANT TO DELETE?","QUESTION MESSAGE",JOptionPane.YES_NO_OPTION);
        if(option==0){
        deleteData();
         JOptionPane.showMessageDialog(this, "DELETED SUCCESSFULLY");
        }
        }
        else{
             JOptionPane.showMessageDialog(this, "**SELECT ANY SINGLE ROW IF YOU WANT TO DELETE ANY DATA**");
        }
    }//GEN-LAST:event_deleteJBActionPerformed
public javax.swing.JButton billJB(){
    return billJB;
}
public javax.swing.JButton deleteJB(){
    return deleteJB;
}
public javax.swing.JButton backJB(){
    return backJB;
}
public javax.swing.JButton logoutJB(){
    return logoutJB;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPatientDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPatientDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPatientDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPatientDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPatientDetailsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJB;
    private javax.swing.JButton billJB;
    private javax.swing.JButton deleteJB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutJB;
    private javax.swing.JTable patientDetailsJTable;
    private javax.swing.JButton refreshJB;
    // End of variables declaration//GEN-END:variables
}
