/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Fame
 */
public class ViewPatientDetails extends javax.swing.JFrame {
FileHandlerPatient f=new FileHandlerPatient();

    /**
     * Creates new form ViewPatientDetails
     */
    public ViewPatientDetails() {
        super("****PATIENT DETAILS****");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        patientIdJLabel = new javax.swing.JLabel();
        patientIdJField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientDetailsJTA = new javax.swing.JTextArea();
        backJB = new javax.swing.JButton();
        submitJB = new javax.swing.JButton();
        logoutJB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("VIEW PATIENT DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 11, -1, -1));

        patientIdJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        patientIdJLabel.setForeground(new java.awt.Color(255, 0, 51));
        patientIdJLabel.setText("PATIENT ID:");
        getContentPane().add(patientIdJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 84, -1, -1));

        patientIdJField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientIdJFieldMouseClicked(evt);
            }
        });
        getContentPane().add(patientIdJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 80, 184, 29));

        patientDetailsJTA.setColumns(20);
        patientDetailsJTA.setRows(5);
        jScrollPane1.setViewportView(patientDetailsJTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 260, 120));

        backJB.setBackground(new java.awt.Color(255, 102, 102));
        backJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Go-back-icon.png")); // NOI18N
        backJB.setText("BACK");
        backJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBActionPerformed(evt);
            }
        });
        getContentPane().add(backJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 263, 130, 37));

        submitJB.setBackground(new java.awt.Color(255, 51, 204));
        submitJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Done-icon.png")); // NOI18N
        submitJB.setText("SUBMIT");
        submitJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJBActionPerformed(evt);
            }
        });
        getContentPane().add(submitJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 263, 130, 37));

        logoutJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\log out.png")); // NOI18N
        logoutJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJBActionPerformed(evt);
            }
        });
        getContentPane().add(logoutJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\viewpdetails.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void patientIdJFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientIdJFieldMouseClicked
        // TODO add your handling code here:
        patientIdJField.setText("");
         patientDetailsJTA.setText("");
             patientDetailsJTA.setEditable(false);
    }//GEN-LAST:event_patientIdJFieldMouseClicked

    private void backJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBActionPerformed
        // TODO add your handling code here:
        PatientFunctionFrame dff=new PatientFunctionFrame();
        dff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backJBActionPerformed

    private void submitJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJBActionPerformed
        // TODO add your handling code here:
        boolean check=false;
        ArrayList<Patients> s=f.read();
        try{
        String id=patientIdJField.getText();
        if(id.equals("")){
            throw new NullPointerException();
        }
        else{
            try{
        int idd=Integer.parseInt(id);
            
            
        s=f.getArray();
        for(int i=0;i<s.size();i++){
            Patients p=s.get(i);
            if(p.getId()==(idd)){
                check=true;
                
                patientDetailsJTA.append(s.get(i).toString());
               }
        }
        if(check==true){
            JOptionPane.showMessageDialog(this, "****RECORD IS FOUND SUCCESSFULLY****","***CONFIRMATION***",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(check==false){
            JOptionPane.showMessageDialog(this, "****RECORD IS NOT FOUND!!!!","***INVALID***",JOptionPane.ERROR_MESSAGE);
        }
        }
            catch(NumberFormatException e){
               JOptionPane.showMessageDialog(this, "****NUMBER FORMAT EXCEPTION OCCURED ENTER ANY INTEGER****","***INVALID***",JOptionPane.ERROR_MESSAGE);
            }
        }
        
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, "****NULL POINTER EXCEPTION,FILL PATIENT ID FIELD****","***INVALID***",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitJBActionPerformed

    private void logoutJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJBActionPerformed
        // TODO add your handling code here:
        DoctorFunctionsFrame dff=new DoctorFunctionsFrame();
        dff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutJBActionPerformed
public javax.swing.JButton backJB(){
    return backJB;
}
public javax.swing.JButton logoutJB(){
    return logoutJB;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPatientDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutJB;
    private javax.swing.JTextArea patientDetailsJTA;
    private javax.swing.JTextField patientIdJField;
    private javax.swing.JLabel patientIdJLabel;
    private javax.swing.JButton submitJB;
    // End of variables declaration//GEN-END:variables
}
