/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Fame
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        super("****WELCOME TO PIMS HOSPITAL****");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        AdminJRB = new javax.swing.JRadioButton();
        PatientJRB = new javax.swing.JRadioButton();
        DoctorJRB = new javax.swing.JRadioButton();
        WelcomeBackJB = new javax.swing.JButton();
        SUBMITJB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("SELECT YOUR POSITION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        buttonGroup1.add(AdminJRB);
        AdminJRB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AdminJRB.setText("ADMIN");
        getContentPane().add(AdminJRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        buttonGroup1.add(PatientJRB);
        PatientJRB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PatientJRB.setText("PATIENT");
        PatientJRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientJRBActionPerformed(evt);
            }
        });
        getContentPane().add(PatientJRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        buttonGroup1.add(DoctorJRB);
        DoctorJRB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoctorJRB.setText("DOCTOR");
        getContentPane().add(DoctorJRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        WelcomeBackJB.setBackground(new java.awt.Color(102, 204, 255));
        WelcomeBackJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        WelcomeBackJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Go-back-icon.png")); // NOI18N
        WelcomeBackJB.setText("BACK");
        WelcomeBackJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WelcomeBackJBActionPerformed(evt);
            }
        });
        getContentPane().add(WelcomeBackJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 219, -1, -1));

        SUBMITJB.setBackground(new java.awt.Color(255, 204, 51));
        SUBMITJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SUBMITJB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\Done-icon.png")); // NOI18N
        SUBMITJB.setText("DONE");
        SUBMITJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITJBActionPerformed(evt);
            }
        });
        getContentPane().add(SUBMITJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 219, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fame\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\hospitalmanagementsystem\\Images\\HB 5.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 280));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PatientJRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientJRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientJRBActionPerformed

    private void WelcomeBackJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WelcomeBackJBActionPerformed
        // TODO add your handling code here:
       
        HospitalFrame h=new HospitalFrame();
        this.dispose();
        h.setVisible(true);
        
    }//GEN-LAST:event_WelcomeBackJBActionPerformed

    private void SUBMITJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMITJBActionPerformed
        // TODO add your handling code here:
        
        if(AdminJRB.isSelected()){
            this.dispose();
            AdminFrame a=new AdminFrame();
            a.setVisible(true);
        }
        else if(PatientJRB.isSelected()){
            PatientFunctionFrame pff=new PatientFunctionFrame();
            pff.setVisible(true);
            this.dispose();
        }
        else if(DoctorJRB.isSelected()){
            DoctorStartFrame dsf=new DoctorStartFrame();
            dsf.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "SELECT ANY ONE RADIO BUTTON");
        }
    }//GEN-LAST:event_SUBMITJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AdminJRB;
    private javax.swing.JRadioButton DoctorJRB;
    private javax.swing.JRadioButton PatientJRB;
    private javax.swing.JButton SUBMITJB;
    private javax.swing.JButton WelcomeBackJB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
